spring:
  datasource:
    url: jdbc:mysql://182.61.22.104:3306/DsWdi?useUnicode=true&characterEncoding=utf8
    username: root
    password: miaomiaomiao
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mappers/*.xml
    
server:
  #端口号
  port: 8888
